---
repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.16.0
    hooks:
      - id: stylua # or stylua-system / stylua-github
        args: ["--config-path", "stylua.toml"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.7.1
    hooks:
      - id: yamlfmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.3
          - prettier-plugin-sort-json@1.0.0
