---
repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.16.0
    hooks:
      - id: stylua # or stylua-system / stylua-github
  - repo: https://github.com/google/yamlfmt
    rev: v0.7.1
    hooks:
      - id: yamlfmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ""
    types: [file, js, json, ts, tsx, jsx, javascript, markdown, md]
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.3
          - prettier-plugin-sort-json@1.0.0
