-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
    vim.cmd("highlight clear")
end
vim.g.colors_name = "catppuccin-mocha"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { bg = "#f38ba8", fg = "#1d1b3b" })
hi(0, "@comment.hint", { bg = "#89b4fa", fg = "#1d1b3b" })
hi(0, "@comment.note", { bg = "#89b4fa", fg = "#1d1b3b" })
hi(0, "@comment.todo", { bg = "#f2cdcd", fg = "#1d1b3b" })
hi(0, "@comment.warning", { bg = "#f9e2af", fg = "#1d1b3b" })
hi(0, "@constant.builtin", { fg = "#ffae79" })
hi(0, "@constant.java", { fg = "#73e8d7" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#56caf9" })
hi(0, "@constructor.lua", { fg = "#fcc9c9" })
hi(0, "@constructor.tsx", { fg = "#b2bdff" })
hi(0, "@constructor.typescript", { fg = "#b2bdff" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "Error" })
hi(0, "@field", { fg = "#b2bdff" })
hi(0, "@function.builtin", { fg = "#ffae79" })
hi(0, "@function.builtin.bash", { fg = "#ff7ea6", italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#73e8d7" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#68e0f5" })
hi(0, "@keyword.function", { fg = "#cfa0ff" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#cfa0ff" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#cfa0ff" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label.json", { fg = "#82b4ff" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.interface", { fg = "#fcc9c9" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "Function" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#cad6fd" })
hi(0, "@markup.environment", { fg = "#ffbbed" })
hi(0, "@markup.environment.name", { fg = "#82b4ff" })
hi(0, "@markup.heading", { bold = true, fg = "#82b4ff" })
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = "#fa96a8", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.url", { fg = "#fcded8", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#8aec84" })
hi(0, "@markup.list.unchecked", { fg = "#7881b6" })
hi(0, "@markup.math", { fg = "#82b4ff" })
hi(0, "@markup.raw", { fg = "#73e8d7" })
hi(0, "@markup.strikethrough", { fg = "#cad6fd", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#fa96a8" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = "#b2bdff", italic = true })
hi(0, "@namespace", { fg = "#b2bdff", italic = true })
hi(0, "@number.css", { fg = "#ffae79" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#fa96a8" })
hi(0, "@property", { fg = "#b2bdff" })
hi(0, "@property.class.css", { fg = "#fee19f" })
hi(0, "@property.cpp", { fg = "#cad6fd" })
hi(0, "@property.css", { fg = "#b2bdff" })
hi(0, "@property.id.css", { fg = "#82b4ff" })
hi(0, "@property.toml", { fg = "#82b4ff" })
hi(0, "@property.typescript", { fg = "#b2bdff" })
hi(0, "@punctuation.bracket", { fg = "#8c97c8" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { fg = "#ffbbed" })
hi(0, "@string.plain.css", { fg = "#ffae79" })
hi(0, "@string.regex", { fg = "#ffae79" })
hi(0, "@string.regexp", { fg = "#ffae79" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.symbol", { fg = "#fcc9c9" })
hi(0, "@string.special.symbol.ruby", { fg = "#fcc9c9" })
hi(0, "@string.special.url", { fg = "#fcded8", italic = true, underline = true })
hi(0, "@symbol", { fg = "#fcc9c9" })
hi(0, "@symbol.ruby", { fg = "#fcc9c9" })
hi(0, "@tag", { fg = "#cfa0ff" })
hi(0, "@tag.attribute", { fg = "#73e8d7", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#73e8d7", italic = true })
hi(0, "@tag.delimiter", { fg = "#68e0f5" })
hi(0, "@text", { fg = "#cad6fd" })
hi(0, "@text.danger", { bg = "#f38ba8", fg = "#1d1b3b" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#fa96a8", italic = true })
hi(0, "@text.environment", { fg = "#ffbbed" })
hi(0, "@text.environment.name", { fg = "#82b4ff" })
hi(0, "@text.literal", { fg = "#73e8d7" })
hi(0, "@text.math", { fg = "#82b4ff" })
hi(0, "@text.note", { bg = "#89b4fa", fg = "#1d1b3b" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = "#cad6fd", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#fa96a8" })
hi(0, "@text.title", { bold = true, fg = "#82b4ff" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#f2cdcd", fg = "#1d1b3b" })
hi(0, "@text.todo.checked", { fg = "#8aec84" })
hi(0, "@text.todo.unchecked", { fg = "#7881b6" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#f9e2af", fg = "#1d1b3b" })
hi(0, "@type.builtin", { fg = "#fee19f" })
hi(0, "@type.builtin.c", { fg = "#fee19f" })
hi(0, "@type.builtin.cpp", { fg = "#fee19f" })
hi(0, "@type.css", { fg = "#b2bdff" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#cfa0ff" })
hi(0, "@variable", { fg = "#cad6fd" })
hi(0, "@variable.builtin", { fg = "#ff7ea6" })
hi(0, "@variable.member", { fg = "#b2bdff" })
hi(0, "@variable.parameter", { fg = "#fa96a8" })
hi(0, "AlphaButtons", { fg = "#b2bdff" })
hi(0, "AlphaFooter", { fg = "#fee19f", italic = true })
hi(0, "AlphaHeader", { fg = "#82b4ff" })
hi(0, "AlphaHeaderLabel", { fg = "#ffae79" })
hi(0, "AlphaShortcut", { fg = "#8aec84" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ffae79" })
hi(0, "Character", { fg = "#73e8d7" })
hi(0, "CmpItemAbbr", { fg = "#8c97c8" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#656ca4", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#cad6fd" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#cad6fd" })
hi(0, "CmpItemKind", { fg = "#82b4ff" })
hi(0, "CmpItemKindClass", { fg = "#fee19f" })
hi(0, "CmpItemKindColor", { fg = "#ff7ea6" })
hi(0, "CmpItemKindConstant", { fg = "#ffae79" })
hi(0, "CmpItemKindConstructor", { fg = "#82b4ff" })
hi(0, "CmpItemKindCopilot", { fg = "#73e8d7" })
hi(0, "CmpItemKindEnum", { fg = "#8aec84" })
hi(0, "CmpItemKindEnumMember", { fg = "#ff7ea6" })
hi(0, "CmpItemKindEvent", { fg = "#82b4ff" })
hi(0, "CmpItemKindField", { fg = "#8aec84" })
hi(0, "CmpItemKindFile", { fg = "#82b4ff" })
hi(0, "CmpItemKindFolder", { fg = "#82b4ff" })
hi(0, "CmpItemKindFunction", { fg = "#82b4ff" })
hi(0, "CmpItemKindInterface", { fg = "#fee19f" })
hi(0, "CmpItemKindKeyword", { fg = "#ff7ea6" })
hi(0, "CmpItemKindMethod", { fg = "#82b4ff" })
hi(0, "CmpItemKindModule", { fg = "#82b4ff" })
hi(0, "CmpItemKindOperator", { fg = "#82b4ff" })
hi(0, "CmpItemKindProperty", { fg = "#8aec84" })
hi(0, "CmpItemKindReference", { fg = "#ff7ea6" })
hi(0, "CmpItemKindSnippet", { fg = "#cfa0ff" })
hi(0, "CmpItemKindStruct", { fg = "#82b4ff" })
hi(0, "CmpItemKindText", { fg = "#73e8d7" })
hi(0, "CmpItemKindTypeParameter", { fg = "#82b4ff" })
hi(0, "CmpItemKindUnit", { fg = "#8aec84" })
hi(0, "CmpItemKindValue", { fg = "#ffae79" })
hi(0, "CmpItemKindVariable", { fg = "#fcc9c9" })
hi(0, "CmpItemMenu", { fg = "#cad6fd" })
hi(0, "ColorColumn", { bg = "#313244" })
hi(0, "ColortilsCurrentLine", { bold = true })
hi(0, "Comment", { fg = "#656ca4", italic = true })
hi(0, "Conceal", { fg = "#7881b6" })
hi(0, "Conditional", { fg = "#cfa0ff", italic = true })
hi(0, "Constant", { fg = "#ffae79" })
hi(0, "CurSearch", { bg = "#f38ba8", fg = "#171530" })
hi(0, "Cursor", { bg = "#cdd6f4", fg = "#1d1b3b" })
hi(0, "CursorColumn", { bg = "#181825" })
hi(0, "CursorIM", { bg = "#cdd6f4", fg = "#1d1b3b" })
hi(0, "CursorLine", { bg = "#2a2b3c" })
hi(0, "CursorLineNr", { fg = "#b2bdff" })
hi(0, "DapBreakpoint", { fg = "#ff7ea6" })
hi(0, "DapBreakpointCondition", { fg = "#fee19f" })
hi(0, "DapBreakpointRejected", { fg = "#cfa0ff" })
hi(0, "DapLogPoint", { fg = "#68e0f5" })
hi(0, "DapStopped", { fg = "#fa96a8" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#8aec84" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#515690" })
hi(0, "DapUIBreakpointsInfo", { fg = "#8aec84" })
hi(0, "DapUIBreakpointsPath", { fg = "#68e0f5" })
hi(0, "DapUIDecoration", { fg = "#68e0f5" })
hi(0, "DapUIFloatBorder", { fg = "#68e0f5" })
hi(0, "DapUILineNumber", { fg = "#68e0f5" })
hi(0, "DapUIModifiedValue", { fg = "#ffae79" })
hi(0, "DapUIPlayPause", { fg = "#8aec84" })
hi(0, "DapUIRestart", { fg = "#8aec84" })
hi(0, "DapUIScope", { fg = "#68e0f5" })
hi(0, "DapUISource", { fg = "#b2bdff" })
hi(0, "DapUIStepBack", { fg = "#82b4ff" })
hi(0, "DapUIStepInto", { fg = "#82b4ff" })
hi(0, "DapUIStepOut", { fg = "#82b4ff" })
hi(0, "DapUIStepOver", { fg = "#82b4ff" })
hi(0, "DapUIStop", { fg = "#ff7ea6" })
hi(0, "DapUIStoppedThread", { fg = "#68e0f5" })
hi(0, "DapUIThread", { fg = "#8aec84" })
hi(0, "DapUIType", { fg = "#cfa0ff" })
hi(0, "DapUIUnavailable", { fg = "#414373" })
hi(0, "DapUIValue", { fg = "#68e0f5" })
hi(0, "DapUIVariable", { fg = "#cad6fd" })
hi(0, "DapUIWatchesEmpty", { fg = "#fa96a8" })
hi(0, "DapUIWatchesError", { fg = "#fa96a8" })
hi(0, "DapUIWatchesValue", { fg = "#8aec84" })
hi(0, "DapUIWinSelect", { fg = "#ffae79" })
hi(0, "DashboardCenter", { fg = "#8aec84" })
hi(0, "DashboardDesc", { fg = "#82b4ff" })
hi(0, "DashboardFiles", { fg = "#b2bdff" })
hi(0, "DashboardFooter", { fg = "#fee19f", italic = true })
hi(0, "DashboardHeader", { fg = "#82b4ff" })
hi(0, "DashboardIcon", { bold = true, fg = "#ffbbed" })
hi(0, "DashboardKey", { fg = "#ffae79" })
hi(0, "DashboardMruTitle", { fg = "#68e0f5" })
hi(0, "DashboardProjectTitle", { fg = "#68e0f5" })
hi(0, "DashboardShortCut", { fg = "#ffbbed" })
hi(0, "Delimiter", { fg = "#8c97c8" })
hi(0, "DiagnosticError", { fg = "#ff7ea6", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#ff7ea6" })
hi(0, "DiagnosticFloatingHint", { fg = "#73e8d7" })
hi(0, "DiagnosticFloatingInfo", { fg = "#68e0f5" })
hi(0, "DiagnosticFloatingWarn", { fg = "#fee19f" })
hi(0, "DiagnosticHint", { fg = "#73e8d7", italic = true })
hi(0, "DiagnosticInfo", { fg = "#68e0f5", italic = true })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#6cf671" })
hi(0, "DiagnosticSignError", { fg = "#ff7ea6" })
hi(0, "DiagnosticSignHint", { fg = "#73e8d7" })
hi(0, "DiagnosticSignInfo", { fg = "#68e0f5" })
hi(0, "DiagnosticSignWarn", { fg = "#fee19f" })
hi(0, "DiagnosticUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89dceb", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f9e2af", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#32283a", fg = "#ff7ea6", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#29313e", fg = "#73e8d7", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#283040", fg = "#68e0f5", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#33313a", fg = "#fee19f", italic = true })
hi(0, "DiagnosticWarn", { fg = "#fee19f", italic = true })
hi(0, "DiffAdd", { bg = "#364143" })
hi(0, "DiffChange", { bg = "#25293c" })
hi(0, "DiffDelete", { bg = "#443244" })
hi(0, "DiffText", { bg = "#3e4b6b" })
hi(0, "Directory", { fg = "#82b4ff" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "DropBarIconUISeparator", { fg = "#7881b6" })
hi(0, "DropBarKindArray", { fg = "#cad6fd" })
hi(0, "DropBarKindBoolean", { fg = "#cad6fd" })
hi(0, "DropBarKindBreakStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindCall", { fg = "#cad6fd" })
hi(0, "DropBarKindCaseStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindClass", { fg = "#cad6fd" })
hi(0, "DropBarKindConstant", { fg = "#cad6fd" })
hi(0, "DropBarKindConstructor", { fg = "#cad6fd" })
hi(0, "DropBarKindContinueStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindDeclaration", { fg = "#cad6fd" })
hi(0, "DropBarKindDelete", { fg = "#cad6fd" })
hi(0, "DropBarKindDoStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindElseStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindEnum", { fg = "#cad6fd" })
hi(0, "DropBarKindEnumMember", { fg = "#cad6fd" })
hi(0, "DropBarKindEvent", { fg = "#cad6fd" })
hi(0, "DropBarKindField", { fg = "#cad6fd" })
hi(0, "DropBarKindFile", { fg = "#cad6fd" })
hi(0, "DropBarKindFolder", { fg = "#cad6fd" })
hi(0, "DropBarKindForStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindFunction", { fg = "#cad6fd" })
hi(0, "DropBarKindIdentifier", { fg = "#cad6fd" })
hi(0, "DropBarKindIfStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindInterface", { fg = "#cad6fd" })
hi(0, "DropBarKindKeyword", { fg = "#cad6fd" })
hi(0, "DropBarKindList", { fg = "#cad6fd" })
hi(0, "DropBarKindMacro", { fg = "#cad6fd" })
hi(0, "DropBarKindMarkdownH1", { fg = "#cad6fd" })
hi(0, "DropBarKindMarkdownH2", { fg = "#cad6fd" })
hi(0, "DropBarKindMarkdownH3", { fg = "#cad6fd" })
hi(0, "DropBarKindMarkdownH4", { fg = "#cad6fd" })
hi(0, "DropBarKindMarkdownH5", { fg = "#cad6fd" })
hi(0, "DropBarKindMarkdownH6", { fg = "#cad6fd" })
hi(0, "DropBarKindMethod", { fg = "#cad6fd" })
hi(0, "DropBarKindModule", { fg = "#cad6fd" })
hi(0, "DropBarKindNamespace", { fg = "#cad6fd" })
hi(0, "DropBarKindNull", { fg = "#cad6fd" })
hi(0, "DropBarKindNumber", { fg = "#cad6fd" })
hi(0, "DropBarKindObject", { fg = "#cad6fd" })
hi(0, "DropBarKindOperator", { fg = "#cad6fd" })
hi(0, "DropBarKindPackage", { fg = "#cad6fd" })
hi(0, "DropBarKindProperty", { fg = "#cad6fd" })
hi(0, "DropBarKindReference", { fg = "#cad6fd" })
hi(0, "DropBarKindRepeat", { fg = "#cad6fd" })
hi(0, "DropBarKindScope", { fg = "#cad6fd" })
hi(0, "DropBarKindSpecifier", { fg = "#cad6fd" })
hi(0, "DropBarKindStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindString", { fg = "#cad6fd" })
hi(0, "DropBarKindStruct", { fg = "#cad6fd" })
hi(0, "DropBarKindSwitchStatement", { fg = "#cad6fd" })
hi(0, "DropBarKindType", { fg = "#cad6fd" })
hi(0, "DropBarKindTypeParameter", { fg = "#cad6fd" })
hi(0, "DropBarKindUnit", { fg = "#cad6fd" })
hi(0, "DropBarKindValue", { fg = "#cad6fd" })
hi(0, "DropBarKindVariable", { fg = "#cad6fd" })
hi(0, "DropBarKindWhileStatement", { fg = "#cad6fd" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#1d1b3b" })
hi(0, "Error", { fg = "#ff7ea6" })
hi(0, "ErrorMsg", { bold = true, fg = "#ff7ea6", italic = true })
hi(0, "Exception", { fg = "#cfa0ff" })
hi(0, "FlashBackdrop", { fg = "#656ca4" })
hi(0, "FlashCurrent", { bg = "#1e1e2e", fg = "#ffae79" })
hi(0, "FlashLabel", { bg = "#1e1e2e", bold = true, fg = "#8aec84" })
hi(0, "FlashMatch", { bg = "#1e1e2e", fg = "#b2bdff" })
hi(0, "FlashPrompt", { link = "NormalFloat" })
hi(0, "FloatBorder", { fg = "#82b4ff" })
hi(0, "FloatTitle", { fg = "#a0acda" })
hi(0, "FoldColumn", { fg = "#656ca4" })
hi(0, "FoldPreview", { bg = "#181825", fg = "#cad6fd" })
hi(0, "FoldPreviewBorder", { fg = "#82b4ff" })
hi(0, "Folded", { bg = "#45475a", fg = "#82b4ff" })
hi(0, "Function", { fg = "#82b4ff" })
hi(0, "FzfLuaBorder", { bg = "#10121e" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#95f6ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff393c" })
hi(0, "FzfLuaBufLineNr", { fg = "#00fa99" })
hi(0, "FzfLuaBufName", { fg = "#ffb8ff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebca" })
hi(0, "FzfLuaCursor", { bg = "#cdd6f4", fg = "#1d1b3b" })
hi(0, "FzfLuaCursorLine", { bg = "#2a2b3c" })
hi(0, "FzfLuaCursorLineNr", { fg = "#b2bdff" })
hi(0, "FzfLuaDirIcon", { fg = "#82b4ff" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebca" })
hi(0, "FzfLuaHeaderText", { fg = "#ff393c" })
hi(0, "FzfLuaHelpBorder", { bg = "#10121e" })
hi(0, "FzfLuaHelpNormal", { bg = "#10121e" })
hi(0, "FzfLuaLiveSym", { fg = "#ff393c" })
hi(0, "FzfLuaNormal", { bg = "#10121e" })
hi(0, "FzfLuaPreviewBorder", { bg = "#10121e" })
hi(0, "FzfLuaPreviewNormal", { bg = "#10121e" })
hi(0, "FzfLuaPreviewTitle", { bg = "#10121e" })
hi(0, "FzfLuaScrollBorderEmpty", { bg = "#10121e" })
hi(0, "FzfLuaScrollBorderFull", { bg = "#10121e" })
hi(0, "FzfLuaScrollFloatEmpty", { bg = "#45475a" })
hi(0, "FzfLuaScrollFloatFull", { bg = "#6c7086" })
hi(0, "FzfLuaSearch", { bg = "#7ec9d8", fg = "#171530" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebca" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#ade2ff" })
hi(0, "FzfLuaTitle", { bg = "#10121e" })
hi(0, "GitSignsAdd", { fg = "#8aec84" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#364143" })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { fg = "#8aec84" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#fee19f" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#25293c" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { fg = "#fee19f" })
hi(0, "GitSignsChangedelete", { fg = "#fee19f" })
hi(0, "GitSignsChangedeleteLn", { bg = "#25293c" })
hi(0, "GitSignsChangedeleteNr", { fg = "#fee19f" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#414373" })
hi(0, "GitSignsDelete", { fg = "#ff7ea6" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { fg = "#ff7ea6" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#443244" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { fg = "#457641" })
hi(0, "GitSignsStagedAddLn", { bg = "#364143" })
hi(0, "GitSignsStagedAddNr", { fg = "#457641" })
hi(0, "GitSignsStagedChange", { fg = "#827046" })
hi(0, "GitSignsStagedChangeLn", { bg = "#25293c" })
hi(0, "GitSignsStagedChangeNr", { fg = "#827046" })
hi(0, "GitSignsStagedChangedelete", { fg = "#827046" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#25293c" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#827046" })
hi(0, "GitSignsStagedDelete", { fg = "#873952" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#873952" })
hi(0, "GitSignsStagedTopdelete", { fg = "#873952" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#873952" })
hi(0, "GitSignsTopdelete", { fg = "#ff7ea6" })
hi(0, "GitSignsTopdeleteNr", { fg = "#ff7ea6" })
hi(0, "GitSignsUntracked", { fg = "#8aec84" })
hi(0, "GitSignsUntrackedLn", { bg = "#364143" })
hi(0, "GitSignsUntrackedNr", { fg = "#8aec84" })
hi(0, "GitSignsVirtLnum", { bg = "#443244" })
hi(0, "GlyphPalette1", { fg = "#ff7ea6" })
hi(0, "GlyphPalette2", { fg = "#73e8d7" })
hi(0, "GlyphPalette3", { fg = "#fee19f" })
hi(0, "GlyphPalette4", { fg = "#82b4ff" })
hi(0, "GlyphPalette6", { fg = "#73e8d7" })
hi(0, "GlyphPalette7", { fg = "#cad6fd" })
hi(0, "GlyphPalette9", { fg = "#ff7ea6" })
hi(0, "HlSearchLens", { bg = "#6c7086" })
hi(0, "HlSearchLensNear", { bg = "#7ec9d8", fg = "#171530" })
hi(0, "HlSearchNear", { bg = "#7ec9d8", fg = "#171530" })
hi(0, "HydraAmaranth", { bold = true, fg = "#ff1357" })
hi(0, "HydraBlue", { bold = true, fg = "#4abdff" })
hi(0, "HydraBorder", { fg = "#82b4ff" })
hi(0, "HydraHint", { bg = "#181825", fg = "#cad6fd" })
hi(0, "HydraPink", { bold = true, fg = "#ff4ce1" })
hi(0, "HydraRed", { bold = true, fg = "#ff532d" })
hi(0, "HydraTeal", { bold = true, fg = "#00a1a1" })
hi(0, "IblIndent", { fg = "#2f2e57" })
hi(0, "IblScope", { fg = "#cad6fd" })
hi(0, "Identifier", { fg = "#fcc9c9" })
hi(0, "IlluminatedWordRead", { bg = "#393b4d" })
hi(0, "IlluminatedWordText", { bg = "#393b4d" })
hi(0, "IlluminatedWordWrite", { bg = "#393b4d" })
hi(0, "IncSearch", { bg = "#7ec9d8", fg = "#171530" })
hi(0, "Include", { fg = "#cfa0ff" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#cfa0ff" })
hi(0, "Label", { fg = "#56caf9" })
hi(0, "LineNr", { fg = "#414373" })
hi(0, "LspCodeLens", { fg = "#656ca4" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#ff7ea6" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#73e8d7" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#68e0f5" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#fee19f" })
hi(0, "LspDiagnosticsError", { fg = "#ff7ea6" })
hi(0, "LspDiagnosticsHint", { fg = "#73e8d7" })
hi(0, "LspDiagnosticsInformation", { fg = "#68e0f5" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#89dceb", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#f9e2af", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#ff7ea6", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#73e8d7", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#68e0f5", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#fee19f", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#fee19f" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#2a2b3c", fg = "#656ca4" })
hi(0, "LspReferenceRead", { bg = "#45475a" })
hi(0, "LspReferenceText", { bg = "#45475a" })
hi(0, "LspReferenceWrite", { bg = "#45475a" })
hi(0, "LspSignatureActiveParameter", { fg = "#ffae79" })
hi(0, "Macro", { fg = "#cfa0ff" })
hi(0, "MatchParen", { bg = "#45475a", bold = true, fg = "#ffae79" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#8c97c8" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#8c97c8" })
hi(0, "MiniTrailspace", { fg = "#ff7ea6" })
hi(0, "ModeMsg", { bold = true, fg = "#cad6fd" })
hi(0, "ModesCopy", { bg = "#fab387" })
hi(0, "ModesCopyCursorLine", { bg = "#332a2e" })
hi(0, "ModesCopyCursorLineFold", { bg = "#332a2e" })
hi(0, "ModesCopyCursorLineNr", { bg = "#332a2e" })
hi(0, "ModesCopyCursorLineSign", { bg = "#332a2e" })
hi(0, "ModesDelete", { bg = "#f38ba8" })
hi(0, "ModesDeleteCursorLine", { bg = "#322433" })
hi(0, "ModesDeleteCursorLineFold", { bg = "#322433" })
hi(0, "ModesDeleteCursorLineNr", { bg = "#322433" })
hi(0, "ModesDeleteCursorLineSign", { bg = "#322433" })
hi(0, "ModesInsert", { bg = "#74c7ec" })
hi(0, "ModesInsertCursorLine", { bg = "#1f2d3d" })
hi(0, "ModesInsertCursorLineFold", { bg = "#1f2d3d" })
hi(0, "ModesInsertCursorLineNr", { bg = "#1f2d3d" })
hi(0, "ModesInsertCursorLineSign", { bg = "#1f2d3d" })
hi(0, "ModesInsertModeMsg", { fg = "#56caf9" })
hi(0, "ModesOperator", { link = "ModesDelete" })
hi(0, "ModesVisual", { bg = "#b4befe" })
hi(0, "ModesVisualCursorLine", { bg = "#292c40" })
hi(0, "ModesVisualCursorLineFold", { bg = "#292c40" })
hi(0, "ModesVisualCursorLineNr", { bg = "#292c40" })
hi(0, "ModesVisualCursorLineSign", { bg = "#292c40" })
hi(0, "ModesVisualModeMsg", { fg = "#b2bdff" })
hi(0, "ModesVisualVisual", { bg = "#292c40" })
hi(0, "MoreMsg", { fg = "#82b4ff" })
hi(0, "MsgSeparator", {})
hi(0, "NeoTreeDimText", { fg = "#505050" })
hi(0, "NeoTreeDotfile", { fg = "#626262" })
hi(0, "NeoTreeFadeText1", { fg = "#626262" })
hi(0, "NeoTreeFadeText2", { fg = "#444444" })
hi(0, "NeoTreeFileNameOpened", { bold = true })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#ff8700", italic = true })
hi(0, "NeoTreeGitUntracked", { fg = "#ff8700", italic = true })
hi(0, "NeoTreeMessage", { fg = "#505050", italic = true })
hi(0, "NeoTreeModified", { fg = "#dad863" })
hi(0, "NeoTreeRootName", { bold = true, italic = true })
hi(0, "NeoTreeTabActive", { bold = true })
hi(0, "NeoTreeTabInactive", { bg = "#141414", fg = "#777777" })
hi(0, "NeoTreeTabSeparatorActive", { fg = "#0a0a0a" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#141414", fg = "#101010" })
hi(0, "NeoTreeTitleBar", { bg = "#89b4fa", fg = "#0e1028" })
hi(0, "NeogitBranch", { bold = true, fg = "#ffae79" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#8aec84" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#fee19f" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#ffbbed" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#ff7ea6" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#82b4ff" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#8aec84" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#ffae79" })
hi(0, "NeogitCommitViewHeader", { bg = "#3e4b6b", fg = "#8fbbff" })
hi(0, "NeogitDiffAdd", { bg = "#2b3139", fg = "#74c374" })
hi(0, "NeogitDiffAddHighlight", { bg = "#4d6256", fg = "#91ea95" })
hi(0, "NeogitDiffContext", { bg = "#1e1e2e" })
hi(0, "NeogitDiffContextHighlight", { bg = "#313244" })
hi(0, "NeogitDiffDelete", { bg = "#32283a", fg = "#dd628f" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#674458", fg = "#fd8ab3" })
hi(0, "NeogitDiffHeader", { bg = "#1e1e2e", bold = true, fg = "#82b4ff" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#1e1e2e", bold = true, fg = "#ffae79" })
hi(0, "NeogitFilePath", { fg = "#82b4ff", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#82b4ff" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#82b4ff" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#82b4ff" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#b5c1ec" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#8aec84" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#b2bdff" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#ff7ea6" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#fee19f" })
hi(0, "NeogitGraphCyan", { fg = "#82b4ff" })
hi(0, "NeogitGraphGray", { fg = "#b5c1ec" })
hi(0, "NeogitGraphGreen", { fg = "#8aec84" })
hi(0, "NeogitGraphOrange", { fg = "#ffae79" })
hi(0, "NeogitGraphPurple", { fg = "#b2bdff" })
hi(0, "NeogitGraphRed", { fg = "#ff7ea6" })
hi(0, "NeogitGraphWhite", { fg = "#1d1b3b" })
hi(0, "NeogitGraphYellow", { fg = "#fee19f" })
hi(0, "NeogitHunkHeader", { bg = "#282c41", fg = "#4366b2" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#353e5a", fg = "#82b4ff" })
hi(0, "NeogitNotificationError", { fg = "#ff7ea6" })
hi(0, "NeogitNotificationInfo", { fg = "#82b4ff" })
hi(0, "NeogitNotificationWarning", { fg = "#fee19f" })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitPopupActionKey", { fg = "#b2bdff" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#b2bdff" })
hi(0, "NeogitPopupOptionKey", { fg = "#b2bdff" })
hi(0, "NeogitPopupSwitchKey", { fg = "#b2bdff" })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitRemote", { bold = true, fg = "#8aec84" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitTagDistance", { fg = "#82b4ff" })
hi(0, "NeogitTagName", { fg = "#fee19f" })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#b2bdff" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#cfa0ff" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#cfa0ff" })
hi(0, "NoiceCmdline", {})
hi(0, "NoiceCmdlineIcon", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconFilter", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconHelp", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconIncRename", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconInput", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconLua", { fg = "#68e0f5" })
hi(0, "NoiceCmdlineIconSearch", { fg = "#fee19f" })
hi(0, "NoiceCmdlinePopup", { bg = "#10121e" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderIncRename", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#fee19f" })
hi(0, "NoiceCmdlinePopupTitle", { fg = "#68e0f5" })
hi(0, "NoiceCmdlinePrompt", { bold = true, fg = "#82b4ff" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindField", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindText", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#ffbbed" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#ffbbed" })
hi(0, "NoiceConfirm", { bg = "#10121e" })
hi(0, "NoiceConfirmBorder", { fg = "#68e0f5" })
hi(0, "NoiceCursor", { bg = "#cdd6f4", fg = "#1d1b3b" })
hi(0, "NoiceFormatConfirm", { bg = "#2a2b3c" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#45475a", bold = true })
hi(0, "NoiceFormatDate", { fg = "#ffbbed" })
hi(0, "NoiceFormatEvent", { bg = "#10121e" })
hi(0, "NoiceFormatKind", { bg = "#10121e" })
hi(0, "NoiceFormatLevelDebug", { bg = "#10121e" })
hi(0, "NoiceFormatLevelError", { bg = "#32283a", fg = "#ff7ea6", italic = true })
hi(0, "NoiceFormatLevelInfo", { bg = "#283040", fg = "#68e0f5", italic = true })
hi(0, "NoiceFormatLevelOff", { bg = "#10121e" })
hi(0, "NoiceFormatLevelTrace", { bg = "#10121e" })
hi(0, "NoiceFormatLevelWarn", { bg = "#33313a", fg = "#fee19f", italic = true })
hi(0, "NoiceFormatProgressDone", { bg = "#3e5767", fg = "#cad6fd" })
hi(0, "NoiceFormatProgressTodo", { bg = "#2a2b3c" })
hi(0, "NoiceFormatTitle", { bold = true, fg = "#82b4ff" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { bold = true, fg = "#82b4ff" })
hi(0, "NoiceLspProgressSpinner", { fg = "#ffae79" })
hi(0, "NoiceLspProgressTitle", { bg = "#10121e" })
hi(0, "NoiceMini", {})
hi(0, "NoicePopup", { bg = "#181825", fg = "#cad6fd" })
hi(0, "NoicePopupBorder", { fg = "#82b4ff" })
hi(0, "NoicePopupmenu", { bg = "#2b2b3c", fg = "#8c97c8" })
hi(0, "NoicePopupmenuBorder", { fg = "#82b4ff" })
hi(0, "NoicePopupmenuMatch", { fg = "#ffbbed" })
hi(0, "NoicePopupmenuSelected", { bg = "#45475a", bold = true })
hi(0, "NoiceScrollbar", { bg = "#45475a" })
hi(0, "NoiceScrollbarThumb", { bg = "#6c7086" })
hi(0, "NoiceSplit", { bg = "#181825", fg = "#cad6fd" })
hi(0, "NoiceSplitBorder", { fg = "#82b4ff" })
hi(0, "NoiceVirtualText", { bg = "#283040", fg = "#68e0f5", italic = true })
hi(0, "NonText", { bg = "#10121e" })
hi(0, "Normal", { bg = "#10121e" })
hi(0, "NormalFloat", { bg = "#181825", fg = "#cad6fd" })
hi(0, "NormalNC", { bg = "#1e1e2e", fg = "#cad6fd" })
hi(0, "NormalSB", { bg = "#11111b", fg = "#cad6fd" })
hi(0, "Number", { fg = "#ffae79" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#82b4ff" })
hi(0, "NvimTreeFolderIcon", { fg = "#82b4ff" })
hi(0, "NvimTreeFolderName", { fg = "#82b4ff" })
hi(0, "NvimTreeGitDeleted", { fg = "#ff7ea6" })
hi(0, "NvimTreeGitDirty", { fg = "#fee19f" })
hi(0, "NvimTreeGitNew", { fg = "#82b4ff" })
hi(0, "NvimTreeImageFile", { fg = "#cad6fd" })
hi(0, "NvimTreeIndentMarker", { fg = "#656ca4" })
hi(0, "NvimTreeNormal", { bg = "#181825", fg = "#cad6fd" })
hi(0, "NvimTreeOpenedFile", { fg = "#ffbbed" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#82b4ff" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#b2bdff" })
hi(0, "NvimTreeSpecialFile", { fg = "#fcc9c9" })
hi(0, "NvimTreeStatuslineNc", { bg = "#181825", fg = "#171530" })
hi(0, "NvimTreeSymlink", { fg = "#ffbbed" })
hi(0, "NvimTreeWinSeparator", { bg = "#1e1e2e", fg = "#1d1b3b" })
hi(0, "Operator", { fg = "#68e0f5" })
hi(0, "Pmenu", { bg = "#2b2b3c", fg = "#8c97c8" })
hi(0, "PmenuSbar", { bg = "#45475a" })
hi(0, "PmenuSel", { bg = "#45475a", bold = true })
hi(0, "PmenuThumb", { bg = "#6c7086" })
hi(0, "PreProc", { fg = "#ffbbed" })
hi(0, "Question", { fg = "#82b4ff" })
hi(0, "QuickFixLine", { bg = "#45475a", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#82b4ff" })
hi(0, "RainbowDelimiterCyan", { fg = "#73e8d7" })
hi(0, "RainbowDelimiterGreen", { fg = "#8aec84" })
hi(0, "RainbowDelimiterOrange", { fg = "#ffae79" })
hi(0, "RainbowDelimiterRed", { fg = "#ff7ea6" })
hi(0, "RainbowDelimiterViolet", { fg = "#cfa0ff" })
hi(0, "RainbowDelimiterYellow", { fg = "#fee19f" })
hi(0, "Repeat", { fg = "#cfa0ff" })
hi(0, "ScrollbarCursor", { ctermfg = 0, fg = "#cad6fd" })
hi(
    0,
    "ScrollbarCursorHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#cad6fd" }
)
hi(0, "ScrollbarError", { ctermfg = 0, fg = "#ff7ea6" })
hi(
    0,
    "ScrollbarErrorHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#ff7ea6" }
)
hi(0, "ScrollbarGitAdd", { ctermfg = 0, fg = "#8aec84" })
hi(
    0,
    "ScrollbarGitAddHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#8aec84" }
)
hi(0, "ScrollbarGitChange", { ctermfg = 0, fg = "#fee19f" })
hi(
    0,
    "ScrollbarGitChangeHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#fee19f" }
)
hi(0, "ScrollbarGitDelete", { ctermfg = 0, fg = "#ff7ea6" })
hi(
    0,
    "ScrollbarGitDeleteHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#ff7ea6" }
)
hi(0, "ScrollbarHandle", { bg = "#181825", blend = 30, ctermbg = 15 })
hi(0, "ScrollbarHint", { ctermfg = 0, fg = "#73e8d7" })
hi(
    0,
    "ScrollbarHintHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#73e8d7" }
)
hi(0, "ScrollbarInfo", { ctermfg = 0, fg = "#68e0f5" })
hi(
    0,
    "ScrollbarInfoHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#68e0f5" }
)
hi(0, "ScrollbarMisc", { ctermfg = 0, fg = "#cad6fd" })
hi(
    0,
    "ScrollbarMiscHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#cad6fd" }
)
hi(0, "ScrollbarSearch", { ctermfg = 0, fg = "#cad6fd" })
hi(
    0,
    "ScrollbarSearchHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#cad6fd" }
)
hi(0, "ScrollbarWarn", { ctermfg = 0, fg = "#fee19f" })
hi(
    0,
    "ScrollbarWarnHandle",
    { bg = "#181825", blend = 30, ctermbg = 15, ctermfg = 0, fg = "#fee19f" }
)
hi(0, "Search", { bg = "#3e5767", fg = "#cad6fd" })
hi(0, "SignColumn", { fg = "#414373" })
hi(0, "SignColumnSB", { bg = "#11111b", fg = "#414373" })
hi(0, "Special", { fg = "#ffbbed" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#f38ba8", undercurl = true })
hi(0, "SpellCap", { sp = "#f9e2af", undercurl = true })
hi(0, "SpellLocal", { sp = "#89b4fa", undercurl = true })
hi(0, "SpellRare", { sp = "#a6e3a1", undercurl = true })
hi(0, "Statement", { fg = "#cfa0ff" })
hi(0, "StatusLine", { bg = "#181825", fg = "#cad6fd" })
hi(0, "StatusLineNC", { bg = "#181825", fg = "#414373" })
hi(0, "StorageClass", { fg = "#fee19f" })
hi(0, "String", { fg = "#8aec84" })
hi(0, "Structure", { fg = "#fee19f" })
hi(0, "Substitute", { bg = "#45475a", fg = "#ffbbed" })
hi(0, "TSRainbowBlue", { ctermfg = 12, fg = "#2a888c" })
hi(0, "TSRainbowCyan", { ctermfg = 14, fg = "#b2976f" })
hi(0, "TSRainbowGreen", { ctermfg = 10, fg = "#52a358" })
hi(0, "TSRainbowOrange", { ctermfg = 15, fg = "#d95a00" })
hi(0, "TSRainbowRed", { ctermfg = 9, fg = "#d40006" })
hi(0, "TSRainbowViolet", { ctermfg = 13, fg = "#c35089" })
hi(0, "TSRainbowYellow", { ctermfg = 11, fg = "#da9801" })
hi(0, "TabLine", { bg = "#181825", fg = "#414373" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#45475a", fg = "#8aec84" })
hi(0, "Tag", { bold = true, fg = "#b2bdff" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#82b4ff" })
hi(0, "TelescopeMultiIcon", { fg = "#fcc9c9" })
hi(0, "TelescopeMultiSelection", { fg = "#fee19f" })
hi(0, "TelescopeNormal", { bg = "#10121e" })
hi(0, "TelescopePreviewBlock", { fg = "#ffae79" })
hi(0, "TelescopePreviewBorder", { fg = "#82b4ff" })
hi(0, "TelescopePreviewCharDev", { fg = "#ffae79" })
hi(0, "TelescopePreviewDate", { fg = "#82b4ff" })
hi(0, "TelescopePreviewDirectory", { fg = "#82b4ff" })
hi(0, "TelescopePreviewExecute", { fg = "#8aec84" })
hi(0, "TelescopePreviewGroup", { fg = "#ffae79" })
hi(0, "TelescopePreviewHyphen", { bg = "#10121e" })
hi(0, "TelescopePreviewLine", { bg = "#45475a", bold = true })
hi(0, "TelescopePreviewLink", { fg = "#ffbbed" })
hi(0, "TelescopePreviewMatch", { bg = "#3e5767", fg = "#cad6fd" })
hi(0, "TelescopePreviewMessage", { bg = "#10121e" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#10121e" })
hi(0, "TelescopePreviewNormal", { bg = "#10121e" })
hi(0, "TelescopePreviewPipe", { fg = "#ffae79" })
hi(0, "TelescopePreviewRead", { fg = "#ffae79" })
hi(0, "TelescopePreviewSize", { fg = "#8aec84" })
hi(0, "TelescopePreviewSocket", { fg = "#cfa0ff" })
hi(0, "TelescopePreviewSticky", { fg = "#cfa0ff" })
hi(0, "TelescopePreviewTitle", { fg = "#82b4ff" })
hi(0, "TelescopePreviewUser", { fg = "#ffae79" })
hi(0, "TelescopePreviewWrite", { fg = "#cfa0ff" })
hi(0, "TelescopePromptBorder", { fg = "#82b4ff" })
hi(0, "TelescopePromptCounter", { bg = "#10121e" })
hi(0, "TelescopePromptNormal", { bg = "#10121e" })
hi(0, "TelescopePromptPrefix", { fg = "#fcc9c9" })
hi(0, "TelescopePromptTitle", { fg = "#82b4ff" })
hi(0, "TelescopeResultsBorder", { fg = "#82b4ff" })
hi(0, "TelescopeResultsClass", { fg = "#82b4ff" })
hi(0, "TelescopeResultsComment", { fg = "#656ca4", italic = true })
hi(0, "TelescopeResultsConstant", { fg = "#ffae79" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#364143" })
hi(0, "TelescopeResultsDiffChange", { bg = "#25293c" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#443244" })
hi(0, "TelescopeResultsDiffUntracked", { bg = "#10121e" })
hi(0, "TelescopeResultsField", { fg = "#82b4ff" })
hi(0, "TelescopeResultsFunction", { fg = "#82b4ff" })
hi(0, "TelescopeResultsIdentifier", { fg = "#fcc9c9" })
hi(0, "TelescopeResultsLineNr", { fg = "#414373" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", { bg = "#10121e" })
hi(0, "TelescopeResultsNumber", { fg = "#ffae79" })
hi(0, "TelescopeResultsOperator", { fg = "#68e0f5" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#ffbbed" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { fg = "#82b4ff" })
hi(0, "TelescopeResultsVariable", { fg = "#ffbbed" })
hi(0, "TelescopeSelection", { bg = "#313244", bold = true, fg = "#cad6fd" })
hi(0, "TelescopeSelectionCaret", { fg = "#fcc9c9" })
hi(0, "TelescopeTitle", { fg = "#82b4ff" })
hi(0, "Title", { bold = true, fg = "#82b4ff" })
hi(0, "Todo", { bg = "#f2cdcd", bold = true, fg = "#1d1b3b" })
hi(0, "TodoBgFIX", { bg = "#f38ba8", bold = true, fg = "#0e1028" })
hi(0, "TodoBgHACK", { bg = "#f9e2af", bold = true, fg = "#0e1028" })
hi(0, "TodoBgNOTE", { bg = "#94e2d5", bold = true, fg = "#0e1028" })
hi(0, "TodoBgPERF", { bg = "#f2cdcd", bold = true, fg = "#0e1028" })
hi(0, "TodoBgTEST", { bg = "#f2cdcd", bold = true, fg = "#0e1028" })
hi(0, "TodoBgTODO", { bg = "#89dceb", bold = true, fg = "#0e1028" })
hi(0, "TodoBgWARN", { bg = "#f9e2af", bold = true, fg = "#0e1028" })
hi(0, "TodoFgFIX", { fg = "#ff7ea6" })
hi(0, "TodoFgHACK", { fg = "#fee19f" })
hi(0, "TodoFgNOTE", { fg = "#73e8d7" })
hi(0, "TodoFgPERF", { fg = "#fcc9c9" })
hi(0, "TodoFgTEST", { fg = "#fcc9c9" })
hi(0, "TodoFgTODO", { fg = "#68e0f5" })
hi(0, "TodoFgWARN", { fg = "#fee19f" })
hi(0, "TodoSignFIX", { fg = "#ff7ea6" })
hi(0, "TodoSignHACK", { fg = "#fee19f" })
hi(0, "TodoSignNOTE", { fg = "#73e8d7" })
hi(0, "TodoSignPERF", { fg = "#fcc9c9" })
hi(0, "TodoSignTEST", { fg = "#fcc9c9" })
hi(0, "TodoSignTODO", { fg = "#68e0f5" })
hi(0, "TodoSignWARN", { fg = "#fee19f" })
hi(0, "Type", { fg = "#fee19f" })
hi(0, "UfoFoldedEllipsis", { bg = "#89b4fa", fg = "#100f24" })
hi(0, "UfoFoldedFg", { fg = "#b2bdff" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", {})
hi(0, "Visual", { bg = "#45475a", bold = true })
hi(0, "VisualNOS", { bg = "#45475a", bold = true })
hi(0, "WarningMsg", { fg = "#fee19f" })
hi(0, "WhichKey", { fg = "#82b4ff" })
hi(0, "WhichKeyBorder", { fg = "#82b4ff" })
hi(0, "WhichKeyDesc", { fg = "#fcc9c9" })
hi(0, "WhichKeyFloat", { bg = "#181825", fg = "#cad6fd" })
hi(0, "WhichKeyGroup", { fg = "#cfa0ff" })
hi(0, "WhichKeySeparator", { fg = "#656ca4", italic = true })
hi(0, "WhichKeyValue", { fg = "#656ca4", italic = true })
hi(0, "Whitespace", { fg = "#414373" })
hi(0, "WildMenu", { bg = "#6c7086" })
hi(0, "WinBar", { fg = "#fcded8" })
hi(0, "WinSeparator", { fg = "#100f24" })
hi(0, "YankyPut", { bg = "#3e5767", fg = "#cad6fd" })
hi(0, "YankyYanked", { bg = "#3e5767", fg = "#cad6fd" })
hi(0, "debugBreakpoint", { bg = "#1e1e2e", fg = "#656ca4" })
hi(0, "debugPC", { bg = "#11111b" })
hi(0, "diffAdded", { fg = "#8aec84" })
hi(0, "diffChanged", { fg = "#82b4ff" })
hi(0, "diffFile", { fg = "#82b4ff" })
hi(0, "diffIndexLine", { fg = "#73e8d7" })
hi(0, "diffLine", { fg = "#656ca4" })
hi(0, "diffNewFile", { fg = "#ffae79" })
hi(0, "diffOldFile", { fg = "#fee19f" })
hi(0, "diffRemoved", { fg = "#ff7ea6" })
hi(0, "gitcommitSummary", { fg = "#fcded8", italic = true })
hi(0, "healthError", { fg = "#ff7ea6" })
hi(0, "healthSuccess", { fg = "#73e8d7" })
hi(0, "healthWarning", { fg = "#fee19f" })
hi(0, "htmlH1", { bold = true, fg = "#ffbbed" })
hi(0, "htmlH2", { bold = true, fg = "#82b4ff" })
hi(0, "illuminatedCurWord", { bg = "#45475a" })
hi(0, "illuminatedWord", { bg = "#45475a" })
hi(0, "incline__gui_bolditalic", { bold = true, italic = true })
hi(0, "incline__guifg_51a0cf", { fg = "#2ca1df" })
hi(0, "lCursor", { bg = "#cdd6f4", fg = "#1d1b3b" })
hi(0, "lualine_a_command", { bg = "#fab387", bold = true, fg = "#1d1b3b" })
hi(0, "lualine_a_inactive", { bg = "#181825", fg = "#82b4ff" })
hi(0, "lualine_a_insert", { bg = "#a6e3a1", bold = true, fg = "#1d1b3b" })
hi(0, "lualine_a_normal", { bg = "#89b4fa", bold = true, fg = "#171530" })
hi(0, "lualine_a_replace", { bg = "#f38ba8", bold = true, fg = "#1d1b3b" })
hi(0, "lualine_a_terminal", { bg = "#a6e3a1", bold = true, fg = "#1d1b3b" })
hi(0, "lualine_a_visual", { bg = "#cba6f7", bold = true, fg = "#1d1b3b" })
hi(0, "lualine_b_command", { bg = "#313244", fg = "#ffae79" })
hi(0, "lualine_b_diagnostics_error_command", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_error_inactive", { bg = "#181825", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_error_insert", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_error_normal", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_error_replace", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_error_terminal", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_error_visual", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diagnostics_hint_command", { bg = "#313244", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_hint_inactive", { bg = "#181825", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_hint_insert", { bg = "#313244", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_hint_normal", { bg = "#313244", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_hint_replace", { bg = "#313244", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_hint_terminal", { bg = "#313244", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_hint_visual", { bg = "#313244", fg = "#73e8d7" })
hi(0, "lualine_b_diagnostics_info_command", { bg = "#313244", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_info_inactive", { bg = "#181825", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_info_insert", { bg = "#313244", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_info_normal", { bg = "#313244", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_info_replace", { bg = "#313244", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_info_terminal", { bg = "#313244", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_info_visual", { bg = "#313244", fg = "#68e0f5" })
hi(0, "lualine_b_diagnostics_warn_command", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diagnostics_warn_inactive", { bg = "#181825", fg = "#fee19f" })
hi(0, "lualine_b_diagnostics_warn_insert", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diagnostics_warn_normal", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diagnostics_warn_replace", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diagnostics_warn_terminal", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diagnostics_warn_visual", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_added_command", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_diff_added_inactive", { bg = "#181825", fg = "#8aec84" })
hi(0, "lualine_b_diff_added_insert", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_diff_added_normal", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_diff_added_replace", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_diff_added_terminal", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_diff_added_visual", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_diff_modified_command", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_modified_inactive", { bg = "#181825", fg = "#fee19f" })
hi(0, "lualine_b_diff_modified_insert", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_modified_normal", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_modified_replace", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_modified_terminal", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_modified_visual", { bg = "#313244", fg = "#fee19f" })
hi(0, "lualine_b_diff_removed_command", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diff_removed_inactive", { bg = "#181825", fg = "#ff7ea6" })
hi(0, "lualine_b_diff_removed_insert", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diff_removed_normal", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diff_removed_replace", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diff_removed_terminal", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_diff_removed_visual", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_inactive", { bg = "#181825", bold = true, fg = "#414373" })
hi(0, "lualine_b_insert", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_normal", { bg = "#313244", fg = "#82b4ff" })
hi(0, "lualine_b_replace", { bg = "#313244", fg = "#ff7ea6" })
hi(0, "lualine_b_terminal", { bg = "#313244", fg = "#8aec84" })
hi(0, "lualine_b_visual", { bg = "#313244", fg = "#cfa0ff" })
hi(0, "lualine_c_inactive", { bg = "#181825", fg = "#656ca4" })
hi(0, "lualine_c_normal", { bg = "#181825", fg = "#cad6fd" })
hi(
    0,
    "lualine_transitional_lualine_a_command_to_lualine_b_command",
    { bg = "#313244", fg = "#ffae79" }
)
hi(
    0,
    "lualine_transitional_lualine_a_insert_to_lualine_b_insert",
    { bg = "#313244", fg = "#8aec84" }
)
hi(
    0,
    "lualine_transitional_lualine_a_normal_to_lualine_b_normal",
    { bg = "#313244", fg = "#82b4ff" }
)
hi(
    0,
    "lualine_transitional_lualine_b_command_to_lualine_x_7_command",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(
    0,
    "lualine_transitional_lualine_b_diff_removed_command_to_lualine_c_normal",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(
    0,
    "lualine_transitional_lualine_b_diff_removed_insert_to_lualine_c_normal",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(
    0,
    "lualine_transitional_lualine_b_diff_removed_normal_to_lualine_c_normal",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(
    0,
    "lualine_transitional_lualine_b_insert_to_lualine_x_7_insert",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(
    0,
    "lualine_transitional_lualine_b_normal_to_lualine_c_normal",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(
    0,
    "lualine_transitional_lualine_b_normal_to_lualine_x_7_normal",
    { bg = "#181825", fg = "#2f2e57" }
)
hi(0, "lualine_x_7_command", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "lualine_x_7_inactive", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "lualine_x_7_insert", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "lualine_x_7_normal", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "lualine_x_7_replace", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "lualine_x_7_terminal", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "lualine_x_7_visual", { bg = "#181825", fg = "#ff9c5d" })
hi(0, "markdownCode", { fg = "#fcc9c9" })
hi(0, "markdownCodeBlock", { fg = "#fcc9c9" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#ffae79" })
hi(0, "markdownLinkText", { fg = "#82b4ff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#1e1e2e", fg = "#cad6fd" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#fcc9c9" })
hi(0, "mkdCodeStart", { bold = true, fg = "#fcc9c9" })
hi(0, "qfFileName", { fg = "#82b4ff" })
hi(0, "qfLineNr", { fg = "#fee19f" })
hi(0, "rainbow1", { fg = "#ff7ea6" })
hi(0, "rainbow2", { fg = "#ffae79" })
hi(0, "rainbow3", { fg = "#fee19f" })
hi(0, "rainbow4", { fg = "#8aec84" })
hi(0, "rainbow5", { fg = "#56caf9" })
hi(0, "rainbow6", { fg = "#b2bdff" })
hi(0, "zshKSHFunction", { link = "Function" })

-- No terminal colors defined
