return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  version = false,
  lazy = vim.fn.argc(-1) == 0,
  event = { "VeryLazy" },
  cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
  install_dir = vim.fn.stdpath("data") .. '/site',
  opts_extend = { "ensure_installed" },
  build = ":TSUpdate",

  opts = {
    indent = { enable = true },
    highlight = { enable = true },
    folds = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "graphql",
      "groovy",
      "html",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "json5",
      "jsonnet",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "nim",
      "printf",
      "proto",
      "python",
      "query",
      "regex",
      "requirements",
      "rst",
      "rust",
      "ssh_config",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  },
}
