local kinds = require("plugins.mini-pickers.kinds")

describe("mini-pickers.kinds", function()
  describe("for_filetype", function()
    it("keeps declaration kinds", function()
      local kept = assert(kinds.for_filetype("go"))
      assert.is_true(kept.Function)
      assert.is_true(kept.Class)
    end)

    it("keeps nothing back for data filetypes, where every kind is structure", function()
      assert.is_nil(kinds.for_filetype("toml"))
      assert.is_nil(kinds.for_filetype("json"))
      assert.is_nil(kinds.for_filetype("markdown"))
    end)

    it("keeps Package for languages that use it for real packages", function()
      assert.is_true(assert(kinds.for_filetype("go")).Package)
    end)
  end)
end)
